#let content = (
  en: (
    title: "Accessibility Analysis Document",
    project: "Project 1",
    author: "Author",
    date: "Date",
    course: "Course",
    course_name: "Universal Design",
    wcag_title: "WCAG principles assesment (pour)",
    perceivable: "Precivable",
    perceivable_items: (
      "Text contarst: Body text (black on white) and headers (white on dark blue) provide very high contrast, meeting WCAG AAA requirements (>7:1)",
      "Font: size Headers and body text are readable and appropriately differentiated.",
      "Visual structure: Clear sections divisions, appropriate spacing",
      "Footer: footer text (light gray) may not meet minimum WCAG AA contrast (4.5:1)",
    ),
    perceivable_checked: (true, true, true, false),
    operable: "Operable",
    operable_items: (
      "Navigation: No element animations. Slide transitions controlled by clicks or scrolling",
      "Progress bar: visual indication of slide number and presentation progress",
      "Table of contents: Logical structure with outline facilitating navigation",
    ),
    operable_checked: (true, true, true),
    understandable: "Understandable",
    understandable_items: (
      "Heading hierarchy: Correct structure (title, section, subsections).",
      "Language: Document language set (english or polish), supporting screen readers.",
      "Content: Clear, direct message without unnecessary embellishments.",
    ),
    understandable_checked: (true, true, true),
    robust: "Robust",
    robust_items: (
      "Alternative text: Alt descriptions added for all images.",
    ),
    robust_checked: (true,),
    issues_title: "IDENTIFIED ACCESSIBILITY ISSUES",
    issue1_title: "Footer text contrast",
    issue1_problem: "Issue: Light gray footer text may not meet minimum 4.5:1 contrast required by WCAG AA.",
    issue1_impact: "Impact: Reduced readability for visually impaired users.",
    issue1_solution: "Solution: Remove footer allowing user to concentrate on more valuable information",
    issue2_title: "Unreabadle text on the slide #4",
    issue2_problem: "Issue: text in the screenshot is too small for comfortable reading",
    issue2_impact: "Impact: Doesnt impact the presentation. Screenshot is purely decorative anyway",
    issue3_title: "PDF metadata verification",
    issue3_problem: "Issue: Uncertainty whether image alternative text is embedded in PDF structure.",
    issue3_impact: "Impact: Screen readers may not read image descriptions.",
    strengths_title: "ACCESSIBILITY STRENGTHS",
    strengths_items: (
      "Very high contrast for body text and headers",
      "No element animations (accessibility requirement)",
      "Manual transitions (no automatic slide changes)",
      "Logical structure with clear hierarchy",
      "Progress bar facilitating orientation",
      "Appropriate font sizes",
      "Consistent, predictable layout",
    ),
    conclusions_title: "CONCLUSIONS",
    conclusions_text: "The presentation meets most WCAG 2.0 Level AA digital accessibility requirements.\nMain issues concern footer text contrast",
  ),
  pl: (
    title: "Dokument analizy dostępności",
    project: "Projekt 1",
    author: "Autor",
    date: "Data",
    course: "Kurs",
    course_name: "Projektowanie Uniwersalne",
    wcag_title: "Ocena zasad WCAG (pour)",
    perceivable: "Postrzegalny",
    perceivable_items: (
      "Kontrast tekstu: Tekst główny (czarny na białym) i nagłówki (białe na ciemnoniebieskim) zapewniają bardzo wysoki kontrast, spełniając wymogi WCAG AAA (>7:1)",
      "Czcionka: rozmiar Nagłówki i tekst główny są czytelne i odpowiednio zróżnicowane.",
      "Struktura wizualna: Wyraźne podziały sekcji, odpowiednie odstępy",
      "Stopka: tekst stopki (jasnoszary) może nie spełniać minimalnego kontrastu WCAG AA (4.5:1)",
    ),
    perceivable_checked: (true, true, true, false),
    operable: "Obsługiwalny",
    operable_items: (
      "Nawigacja: Brak animacji elementów. Przejścia slajdów kontrolowane kliknięciami lub przewijaniem",
      "Pasek postępu: wizualna wskazówka numeru slajdu i postępu prezentacji",
      "Spis treści: Logiczna struktura ze schematem ułatwiającym nawigację",
    ),
    operable_checked: (true, true, true),
    understandable: "Zrozumiały",
    understandable_items: (
      "Hierarchia nagłówków: Prawidłowa struktura (tytuł, sekcja, podsekcje).",
      "Język: Język dokumentu ustawiony (angielski lub polski), wspierający czytniki ekranowe.",
      "Treść: Jasny, bezpośredni przekaz bez zbędnych upiększeń.",
    ),
    understandable_checked: (true, true, true),
    robust: "Solidny",
    robust_items: (
      "Tekst alternatywny: Opisy alternatywne dodane do wszystkich obrazów.",
    ),
    robust_checked: (true,),
    issues_title: "ZIDENTYFIKOWANE PROBLEMY Z DOSTĘPNOŚCIĄ",
    issue1_title: "Kontrast tekstu w stopce",
    issue1_problem: "Problem: Jasnoszary tekst stopki może nie spełniać minimalnego kontrastu 4.5:1 wymaganego przez WCAG AA.",
    issue1_impact: "Wpływ: Zmniejszona czytelność dla użytkowników z wadami wzroku.",
    issue1_solution: "Rozwiązanie: Usunięcie stopki, pozwalające użytkownikowi skupić się na bardziej wartościowych informacjach",
    issue2_title: "Nieczytelny tekst na slajdzie #4",
    issue2_problem: "Problem: tekst na zrzucie ekranu jest za mały dla wygodnego czytania",
    issue2_impact: "Wpływ: Nie wpływa na prezentację. Zrzut ekranu jest i tak wyłącznie dekoracyjny",
    issue3_title: "Weryfikacja metadanych PDF",
    issue3_problem: "Problem: Niepewność, czy tekst alternatywny obrazów jest osadzony w strukturze PDF.",
    issue3_impact: "Wpływ: Czytniki ekranowe mogą nie odczytywać opisów obrazów.",
    strengths_title: "MOCNE STRONY DOSTĘPNOŚCI",
    strengths_items: (
      "Bardzo wysoki kontrast dla tekstu głównego i nagłówków",
      "Brak animacji elementów (wymóg dostępności)",
      "Ręczne przejścia (brak automatycznej zmiany slajdów)",
      "Logiczna struktura z wyraźną hierarchią",
      "Pasek postępu ułatwiający orientację",
      "Odpowiednie rozmiary czcionek",
      "Spójny, przewidywalny układ",
    ),
    conclusions_title: "WNIOSKI",
    conclusions_text: "Prezentacja spełnia większość wymogów dostępności cyfrowej WCAG 2.0 Level AA.\nGłówne problemy dotyczą kontrastu tekstu w stopce",
  ),
)
