#let content = (
  en: (
    title: "Accessibility Analysis Document",
    project: "Project 1/2",
    author: "Yaroslav Zubakha",
    date: "Date",
    course: "Course",
    course_name: "Universal Design",
    wcag_title: "WCAG principles assessment",
    perceivable: "Perceivable",
    perceivable_items: (
      "Text contrast: Body text (black on white) provides high contrast, meeting WCAG AA requirements (>4.5:1)",
      "Font: Size 12pt is readable and appropriate.",
      "Visual structure: Clear section headings, appropriate spacing",
      "Images: All images have alternative text.",
    ),
    perceivable_checked: (true, true, true, true),
    operable: "Operable",
    operable_items: (
      "Navigation: Structure with headings facilitates navigation.",
      "Page numbering: Allows orientation in the document.",
      "Table of contents: Logical structure.",
    ),
    operable_checked: (true, true, true),
    understandable: "Understandable",
    understandable_items: (
      "Heading hierarchy: Correct structure (title, sections).",
      "Language: Document language set to Polish, supporting screen readers.",
      "Content: Clear, direct content without unnecessary embellishments.",
    ),
    understandable_checked: (true, true, true),
    robust: "Robust",
    robust_items: (
      "Alternative text: Alt descriptions added for all images.",
      "Format: PDF generated from Typst, compliant with standards.",
    ),
    robust_checked: (true, true),
    issues_title: "IDENTIFIED ACCESSIBILITY ISSUES",
    issue1_title: "No issues",
    issue1_problem: "No significant accessibility issues.",
    issue1_impact: "No impact.",
    issue1_solution: "No corrections needed.",
    strengths_title: "ACCESSIBILITY STRENGTHS",
    strengths_items: (
      "High text contrast",
      "No animations or interactive elements",
      "Logical structure with heading hierarchy",
      "Alternative text for images",
      "Appropriate font sizes",
      "Consistent layout",
    ),
    conclusions_title: "CONCLUSIONS",
    conclusions_text: "The document meets WCAG 2.0 Level AA digital accessibility requirements. Main strengths include high contrast and structure.",
  ),
  pl: (
    title: "Dokument analizy dostępności",
    project: "Projekt 1/2",
    author: "Yaroslav Zubakha",
    date: "Data",
    course: "Kurs",
    course_name: "Projektowanie Uniwersalne",
    wcag_title: "Ocena zasad WCAG",
    perceivable: "Postrzegalny",
    perceivable_items: (
      "Kontrast tekstu: Tekst główny (czarny na białym) zapewnia wysoki kontrast, spełniając wymogi WCAG AA (>4.5:1)",
      "Czcionka: Rozmiar 12pt jest czytelny i odpowiedni.",
      "Struktura wizualna: Wyraźne nagłówki sekcji, odpowiednie odstępy",
      "Obrazy: Wszystkie obrazy mają tekst alternatywny.",
    ),
    perceivable_checked: (true, true, true, true),
    operable: "Obsługiwalny",
    operable_items: (
      "Nawigacja: Struktura z nagłówkami ułatwia nawigację.",
      "Numeracja stron: Umożliwia orientację w dokumencie.",
      "Spis treści: Logiczna struktura.",
    ),
    operable_checked: (true, true, true),
    understandable: "Zrozumiały",
    understandable_items: (
      "Hierarchia nagłówków: Prawidłowa struktura (tytuł, sekcje).",
      "Język: Język dokumentu ustawiony na polski, wspierający czytniki ekranowe.",
      "Treść: Jasna, bezpośrednia treść bez zbędnych ozdobników.",
    ),
    understandable_checked: (true, true, true),
    robust: "Solidny",
    robust_items: (
      "Tekst alternatywny: Opisy alternatywne dodane do wszystkich obrazów.",
      "Format: PDF wygenerowany z Typst, zgodny ze standardami.",
    ),
    robust_checked: (true, true),
    issues_title: "ZIDENTYFIKOWANE PROBLEMY Z DOSTĘPNOŚCIĄ",
    issue1_title: "Brak problemów",
    issue1_problem: "Brak znaczących problemów z dostępnością.",
    issue1_impact: "Brak wpływu.",
    issue1_solution: "Brak konieczności poprawek.",
    strengths_title: "MOCNE STRONY DOSTĘPNOŚCI",
    strengths_items: (
      "Wysoki kontrast tekstu",
      "Brak animacji czy elementów interaktywnych",
      "Logiczna struktura z hierarchią nagłówków",
      "Tekst alternatywny dla obrazów",
      "Odpowiednie rozmiary czcionek",
      "Spójny układ",
    ),
    conclusions_title: "WNIOSKI",
    conclusions_text: "Dokument spełnia wymogi dostępności cyfrowej WCAG 2.0 Level AA. Główne mocne strony to wysoki kontrast i struktura.",
  ),
)

